sudo: false

language: node_js

node_js:
  - node

install: 
  - npm ci

script:
  - npm run lint
  - npm run test:coveralls

notifications:
  email: false

services:
  - postgresql
cache:
  directories:
    - node_modules
    
before_script:
  - npm install
  - psql -c 'create database travis_ci_test;' -U postgres

after_success:
  - npm run coverage
  - npm run report-coverage
  - npm run coveralls